<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<!-- Targeting minimum supported versions here despite package targeting lower in some cases -->
		<TargetFrameworks>net8.0</TargetFrameworks>
		<RootNamespace>TagHelperPack.Sample</RootNamespace>
		<DebugType>full</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\TagHelperPack\TagHelperPack.csproj" />
		<PackageReference Include="Microsoft.Extensions.DependencyModel" Version="8.0.*" />
	</ItemGroup>

</Project>
